import BlurredBg from "@/components/BlurredBg";
import Footer from "@/components/Footer";
import NavBar from "@/components/Navbar";
import { PortableTextComponents } from "@/components/PortableText";
import { Separator } from "@/components/ui/separator";

import { REFUND_POLICY_QUERY } from "@/sanity/actions/queries";
import { sanityFetch } from "@/sanity/lib/client";

import { PortableText } from "@portabletext/react";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Our team",
	description: "Generated by create next app",
};

const RefundPolicy = async () => {
	const policy = await sanityFetch<getPolicy>({ query: REFUND_POLICY_QUERY });
	return (
		<main className="pt-16">
			<BlurredBg />
			<NavBar />
			<section className="mx-auto h-auto w-full max-w-3xl px-5 py-28">
				<section className="flex w-full flex-col justify-start space-y-5">
					<h4>{policy.title}</h4>
					<span className="dark:text-white">
						Last updated:{" "}
						{new Date(policy._updatedAt).toLocaleDateString("en-US", {
							year: "numeric",
							month: "long",
							day: "numeric",
						})}
					</span>
				</section>
				<Separator className="my-4" />
				<PortableText
					value={policy.content}
					components={PortableTextComponents}
				/>
			</section>
			<Footer />
		</main>
	);
};

export default RefundPolicy;
